### ISSUE TITLE
Counter ps1 to unlock everything

### ISSUE THREAD

**Issue by AndrzejRPiotrowski** [simeononsecurity/Windows-Hardening-CTF#1]
Hello,

I have used this PS1 but i cannot go back to my old settings. Please help as i can't work :)

Made a big mistake to take this to my laptop with some data :D

Is there any backup plan ?

**Comment by simeononsecurity** [comment]
Hello @AndrzejRPiotrowski , please read the about section before running random scripts on the internet "Only for use during Blue-Team Competitions" is said pretty clearly. 
You can try to use a windows restore point to revert the changes, but it won't get everything.
The best way is to reinstall windows.
